var modsSocArt5 = [{
	title: 'AGRíCOLA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) tareas pecuarias, agrícolas, forestales, hortícolas, avícolas, apícolas y destinadas a la obtención de frutos o productos primarios; b) transformación artesanal e industrialización de la materia prima producida por la entidad; c) Dictado de cursos, talleres y seminarios relacionados con el rubro y las actividades de la cooperativa; d) organización y participación en ferias agroganaderas; e) comercialización de los productos de la cooperativa.'
}, {
	title: 'AGROPECUARIO',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) tareas pecuarias, agrícolas, forestales, hortícolas, avícolas, apícolas, y destinadas a la obtención de frutos o productos primarios; b) transformación artesanal e industrialización de la materia prima producida por la entidad; c) Dictado de cursos, talleres y seminarios relacionados con el rubro y las actividades de la cooperativa; d) organización y participación en ferias agroganaderas; e) comercialización de los productos de la cooperativa.'
}, {
	title: 'ARTESANÍAS',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Diseño y producción de artesanías urbanas, regionales y relacionadas con el arte originario, con materia prima diversa y con utilización de técnicas tradicionales e/o innovadoras: Alfarería, Artesanía de hierro, Bisutería; Cerámica, Ebanistería, madera, mimbre y junco, hilandería, trabajos artesanales textiles en exposición y comercialización. b) Trabajar sobre la capacitación constante de los/as asociados/as de la comunidad y del sector de la economía social. c) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'ARTÍCULOS DE LIMPIEZA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Producir, fraccionar, envasar, distribuir y/o comercializar artículos de limpieza, de aseo personal, fragancias, aromatizantes de ambiente, y todo lo inherente al cuidado personal y al aseo del hogar y/o la industria.'
}, {
	title: 'CALZADO Y MARROQUINERIA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Fabricación, armado y reparación de calzado, diseño de modelos, fabricación de calzado especial, calzado ortopédico, plantillado, b) Marroquinería en general, confección de vestimentas y producción de artículos de cuero, gamuza, simil cuero u otros materiales: carteras, cintos y otros accesorios. c) fabricación de monturas de cuero para caballo, bozal de cuero, maneas, correones, artículos de cuero en general. d) Dictado de cursos, enseñanza del oficio, realización de desfiles y presentaciones.'
}, {
	title: 'CARGA Y DESCARGA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: operaciones de carga y descarga, manipuleo, movimiento, apilaje, estibaje, paletizado, strichado, racks o cualquier tecnología de acopio por estanterías o módulos, consolidación y desconsolidación de contenedores, quiebre y/o ruptura y/o fraccionamiento de carga con su descarga y servicios complementarios de traslado, acondicionamiento y empaque de materias primas o elaboradas o semielaboradas.'
}, {
	title: 'CARPINTERÍA DE MADERA Y/O METÁLICA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: Diseño y fabricación de: a) Estructuras metálicas de madera y pvc. b) mobiliario para stands. c) Carpintería de obra y aberturas en general. d) Piezas de señalización. e) Sistemas señaléticas. f) Carteleras, marquesinas, ploteados. g) montaje de las estructuras o elementos fabricados h) Pintura al horno vinculada con los puntos anteriores. i) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'COMERCIALIZACIÓN',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: Producción, adquisición, Compra, fraccionamiento, envasado, distribución y/o colocación minorista y/o mayorista de productos de consumo masivo y/o de la Economía Social, incluyendo bebidas, productos alimenticios frescos y procesados, indumentarias comprendidos calzados y bolsos, artículos de limpieza, perfumería, artículos de bazar, juguetería, artículos escolares y de papelería, en el mercado externo e interno. b) Distribución y colocación de los productos en el mercado interno e internacional c) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'CONSTRUCCIÓN',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) La construcción de viviendas colectivas y/o unidades complementarias o de viviendas individuales, y de toda otra obra afín, conexa o complementaria de aquélla o de infraestructura. Asimismo, en razón de la especialidad profesional o técnica de sus asociados, podrá asumir cualquier otro tipo de tareas en obras públicas o privadas. b) Reparación, mantenimiento, mejora y/o construcción de obras públicas y privadas. c) Albañilería, pintura, electricidad, herrería, carpintería, plomería e instalación de redes de luz, agua, gas y/o cloacas y sus respectivas conexiones. d) Fabricación de ladrillos, bloques, y otros elementos para la construcción. e) Señalización, bacheo y otras actividades de mantenimiento; f) Mantenimiento y creación de espacios verdes, zanjeo, desmalezamiento y/o parquización en lugares públicos y/o privados.'
}, {
	title: 'CUIDACOCHES',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: Control de estacionamiento medido de acuerdo a la legislación vigente en la materia.'
}, {
	title: 'CUIDADO DE ADULTOS MAYORES',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Atención y cuidado al adulto mayor, personas con discapacidad y/o personas con enfermedades crónicas, de acuerdo a la normativa vigente en la materia; b) Servicios de acompañamiento y asesoramiento en la vida diaria, administración de medicación por vía oral y de uso externo indicado y/o prescriptos por profesionales habilitados, preparación de alimentos, ingesta asistida, higiene y arreglo personal, acciones preventivas de accidentes, colaboración en las prácticas indicadas por el profesional habilitado; c) Organización de eventos sociales y actividades recreativas y/o ocupacionales destinadas a las personas asistidas; d) Difusión de acciones de promoción sobre cuidados y reinserción social.'
}, {
	title: 'CUIDADO DE INFANCIAS',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Brindar asistencia personalizada, cuidar, acompañar, realizar prevención, estimulación, recreación y pre educación a personas humanas menores de edad, tanto en forma domiciliaria como en espacios institucionales; b) Prestar asistencia en la alimentación, esparcimiento, toma de medicación, higiene y movilización del grupo previamente mencionado. c) Brindar los elementos básicos para la satisfacción de las necesidades fisiológicas, afectivas, psicomotrices, de juego, recreación y socialización para el sano desarrollo de la infancia y su entorno. d) Organización y gestión de espacios propicios para el cuidado y la estimulación de infantes de 45 días a 3 años inclusive. e) Organización de cursos, talleres y eventos de carácter recreativo, lúdico y cultural destinados a la infancia y a las familias.'
}, {
	title: 'ENERGÍAS ALTERNATIVAS',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Diseño, instalación, mantenimiento, ampliación y remodelación de instalaciones de energías, tipos de energías sostenibles y/o energías alternativas . b) Optimización, mantenimiento y desarrollo de sistemas e instalaciones eléctricas, electrónicas y electromecánicas. c) Investigación y dictado de cursos de capacitación en lo concerniente al objeto social.'
}, {
	title: 'ENSEÑANZA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Impartir educación formal y no formal de enseñanza a alumnos en nivel inicial, medio y/o superior; b) Dictado de cursos, jornadas y talleres de carácter científico, literario, artístico, cultural, lúdicos, deportivo y talleres de idiomas. c) La explotación de establecimientos educativos; d) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'FOTOGRAFIA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) diseño, publicación y producción fotográfica, de audiovisuales y de diseños web; b) desarrollar, promocionar, capacitar e implementar proyectos y actividades vinculadas a la industria fotográfica, de audiovisuales y diseños web; c) producción, diagramación y ejecución de programas y contenidos para radio, televisión y redes sociales; d) realización de eventos vinculados a la comunicación.'
}, {
	title: 'GASTRONOMÍA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Elaboración de comida y todo tipo de alimentos para su comercialización, expendio de bebidas para consumo humano; b) Servicios de Lunch y catering para banquetes y eventos; c) Restaurante y rotisería con atención en el local y envío a domicilio; d) Elaboración de productos panificados, amasados, de confitería, repostería, sandwichería; e) Servicios de Catering para instituciones públicas y/o privadas y/o para llevar; f) Elaboración de pastas, amasado y todo lo complementario con las mismas; g) Distribución y colocación de los productos en el mercado nacional e internacional; h) Elaboración y comercialización de dulces y conservas; i) Distribución y colocación de los productos en el mercado interno e internacional; j) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'GESTIÓN DEL CENTRO DE REHABILITACIÓN',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) administración y gestión de centros de prevención y recuperación de personas con consumo problemático de sustancias y/o en situación de vulnerabilidad social y/o económica, incluyendo actividades tales como: recreación, esparcimiento, mantenimiento, alimentación, acompañamiento del núcleo familiar y otras afines, excluyendo actividades relacionadas a la medicina. b) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'GESTION DE ESPACIO CULTURAL',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Gestionar un espacio cultural integral. b) Favorecer y fomentar los emprendimientos creativos de base cultural. c) Auspiciar y generar cursos, charlas, debates, jornadas, talleres y seminarios vinculados a la práctica cultural en todas sus ramas. d) Realizar muestras de pintura, dibujo, escultura, artesanía y/o diseño, obras de teatro, recitales, festivales de música y cine, espectáculos de danza, encuentros literarios, presentaciones de libros, ferias y cualquier otro emprendimiento cultural. e) Realizar transmisiones radiales y/o proyectar producciones audiovisuales de contenido cultural que reflejen el objeto de esta cooperativa. f) Realizar producciones culturales en todo tipo de soporte. g) Ofrecer el servicio de gastronomía acompañando las presentaciones que se realicen en el espacio especialmente instalado para el desarrollo de las actividades artísticas. h) Promocionar la vida asociativa y la participación ciudadana en las tareas comunitarias desde la Pluralidad cultural. i) Realizar investigaciones en el área del Patrimonio Histórico y Arqueológico. j) Generar, auspiciar y/o fomentar actividades vinculadas al turismo cultural. k) Ofrecer el servicio de gastronomía acompañando las presentaciones que se realicen en el espacio especialmente instalado para el desarrollo de las actividades artísticas. l) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'GRAFICA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Producción, elaboración y transformación en sus diferentes etapas y modalidades de artículos que corresponden a las ramas de ediciones y artes gráficas, sus actividades conexas o complementarias, así como la colocación en los mercados de los mismos b) La instalación y puesta en marcha de talleres de imprenta, copiado, troquelado, corte, tareas de diseño gráfico, diseño, preimpresión, impresión en cualquiera de sus formas. c) Colocación en los mercados de diarios y revistas, publicaciones, folletos, folletines, volantes, papeles, membretados, dípticos, trípticos, tarjetas personales y/o empresariales, calcomanías, impresiones de planos y ploteos. d) Encuadernación para la producción de libros, diarios, revistas, folletos, afiches, volantes y/o toda tarea afín y conexa con la industria editorial. e) diseño e impresión en soportes tales como: tela, papel u objetos pasibles de ser impresos, mediante técnicas manuales o mecánicas relativas al estampado, sublimado, serigrafía, copiado y demás actividades afines, conexas o complementarias. f) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'INDUSTRIAS CULTURALES',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: A) Gestionar proyectos de industrias culturales en los sectores: Audiovisual, Artes visuales, Musica, Musica academica, Tango, Danza, Circo, Diseño, Editorial, Folklore, Gastronomía, Hip hop, Infancias, Teatro y Videojuegos. B) Producción, realización y escenificación de programas radiales, televisivos, teatrales, recitales, bailes, espectáculos gastronómicos y otros de las industrias culturales. C) Organización, participación y explotación de todo tipo de espectáculos públicos o privados. D) Asesoría publicitaria: estudio, creación, planeamiento, producción, difusión, publicación, administración de campañas de publicidad y actividades conexas; E) Construcción, reparación, mantenimiento, acondicionamiento y comercialización de estructuras transitorias o complementarias tales como escenario, mangrullos, cabinas, consolas y todo tipo de equipo de video o audio, sistemas de iluminación, digitales, analógicos u otra tecnología adecuada; F) Construcción, reparación, mejora, mantenimiento y acondicionamiento de áreas insonorizadas en locales o establecimientos dedicados a la música y al entretenimiento; F) Construcción de Pantallas acústicas, silenciadores, encabinados de máquinas; G) Diseño y construcción de estudios de grabación y salas de ensayo; H) Contratación de Artistas y Provisión de Operadores de sonido para los shows en vivo, estudios de grabación, radio y cualquier evento. I) Diseño y gráfico, web, industrial y audiovisual para espectáculos; J) Confección textil industrial en serie, confección de ropa y todo tipo de accesorios vinculados a las actividades presentes; K) Servicios de Lunch, expendio de bebidas y catering para espectáculos, L) Promover la educación y capacitación de sus asociados. M) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'JUGUETES-DISEÑO-MANUFACTURERA-TRANSFORMADORA',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Diseño, producción y/o distribución de juegos, juguetes, mobiliario, murales y espacios; b) Diseño gráfico, web, industrial, manual y audiovisual; c) talleres de capacitación en técnicas de diseño y diferentes técnicas artesanales u oficios; d) talleres de juego y creatividad; e) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'MANTENIMIENTO',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Reparación, mantenimiento, mejora y construcción de obras públicas y privadas; Albañilería, pintura, electricidad, herrería, carpintería, plomería e instalación de redes de luz gas, agua y/o cloacas y sus conexiones domiciliarias. b) fabricación de ladrillos, bloques y otros elementos para la construcción; señalización, bacheo y otras actividades de mantenimiento vial. c) Mantenimiento y creación de espacios verdes, zanjeo, desmalezamiento y parquización en lugares públicos y/o privados. d) Asimismo, en razón de la especialidad profesional y técnica de sus asociados podrán asumir cualquier tipo de tareas en obras públicas o privadas, organizar y dictar cursos de capacitación teórico y/o prácticos destinados a los asociados y a la comunidad en general.'
}, {
	title: 'MEDIOS DE COMUNICACION',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) producción, distribución, comercialización y exportación de bienes y servicios en materia audiovisual y teatral, como así también todo lo referido servicios integrales de comunicación, diseño gráfico y web. b) promover el desarrollo cultural a través de las actividades vinculadas a la comunicación, a la industria cultural y a las metodologías de trabajo en red, social, virtual e interpersonal, cualquiera sea el área de su implementación (cultura, educación, salud. etc) a nivel nacional e internacional. c) impresión de diarios, revistas barriales, folletos, dípticos, trípticos tarjetas personales, empresariales, calcomanías. Diagramación, producción y ejecución en programas radiales y televisivos, como así también prestación de servicios integrales de comunicación, diseño y páginas Web. d) Producir, editar y publicar contenidos para medios gráficos audiovisuales (radio, televisión e internet), asesorar para la creación, gestión y renovación tecnológica de medios gráficos y audiovisuales. e) Producción, dirección, ejecución y difusión de noticias, música y programas de contenidos e interés generales por medio masivos de comunicación audiovisual. f) Elaboración y comercialización de pautas publicitarias para medios de comunicación audiovisual, control técnico de emisiones radiofónicas. g) Realización de eventos vinculados a la comunicación, producciones culturales y sociales. h) emitir por cualquier medio técnico señales audiovisuales propias, con o sin repetidoras y su distribución. i) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'MULTI OBJETO INDUSTRIAL',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: Fabricación de plásticas y metálicas: a) Diseño y producción de piezas plásticas o metálicas en todas sus variantes para artefactos del hogar y la industria, b) Diseño y producción de piezas . Inyección de plástico: a) diseño y fabricación de todo tipo de artículos de plástico para el hogar y electrónicos, b) Distribución, comercialización y exportación del producido. Vidrio: a) la fabricación, producción y colocación de vidrios, b) la industria del vidrio en general, fabricación de envases de vidrio, bazar, vajilla y afines, c) Distribución, comercialización y exportación del producido. Capacitación: a) Capacitación de oficios varios mediante talleres, cursos, encuentros y jornadas en materia de: Proyecto de Orientación e Inducción al mundo del Trabajo, Búsqueda de Empleo, Gestión empresarial, Estrategias de aprendizaje, Métodos de enseñanza y Planificación Educativa y/o todo tipo de oficio manual y/o industrial.'
}, {
	title: 'PELUQUERÍA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Servicio de peluquería, manicuría, pedicuría, depilación, masajes, maquillaje, maquillaje artístico y toda otra actividad conexa o complementaria a las anteriormente mencionadas. b) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'PESCA',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) tareas pecuarias, agrícolas, forestales, hortícolas, avícolas, apícolas, ictícolas y destinadas a la obtención de frutos o productos primarios; b) transformación artesanal e industrialización de la materia prima producida por la entidad; c) Dictado de cursos, talleres y seminarios relacionados con el rubro y las actividades de la cooperativa; d) organización y participación en ferias agroganaderas; e) comercialización de los productos de la cooperativa.'
}, {
	title: 'PLANTAS MEDICINALES',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Elaboración de productos en base a la producción orgánica y diversificada de plantas medicinales, aromáticas y/o hierbas para aplicaciones y/o de uso comestible; laboratorios de preparados con plantas medicinales; farmacias vivas. b) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'POLIDEPORTIVO',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Administración y gestión de centros de prevención y recuperación de personas en situación de vulnerabilidad social o económica incluyendo actividades de educación, recreación, esparcimiento, deportivas, culturales, artísticas, taller de oficios y otras afines o conexas, excluyendo actividades relacionadas a la medicina. b) Administrar, fomentar y enseñar el deporte en sus distintas disciplinas y formas, como así también toda actividad física, danzas, bailes y/o actividades culturales que permitan mejorar la calidad de vida de la sociedad. c) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'PRODUCCIÓN DE ALIMENTOS',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) adquisición, elaboración, producción, industrialización, comercialización, almacenamiento, empaque, transporte y colocación de productos alimenticios en el mercado interno e internacional c) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'PRODUCCION EDITORIAL',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Producción editorial y valoración en contenido de enseñanza y divulgación. b) realización de actividades vinculadas a la producción editorial, tales como el diseño, impresión, encuadernado, distribución y comercialización de libros, revistas y toda clase de publicaciones gráficas. c) gestión integral de negocios gráficos, como la compra, venta y distribución de publicaciones e impresiones en general. d) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'PRODUCCION MUSICAL',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Proponer, auspiciar y realizar cursos, charlas-debate, talleres, seminarios sobre: producción musical, ingeniería de sonido, idioma, producción multimedia, producción audiovisual, artes físicas, cine, teatro, danza. b) brindar educación y capacitación en los establecimientos educativos. c) proponer y realizar charlas, cursos, capacitaciones, debates, seminarios, y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'PRODUCCION Y COMERCIALIZACION DE CERVEZA ARTESANAL',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Producción, almacenamiento, comercialización, distribución y transporte de cerveza; b) siembra y cosecha de cebada, lúpulo, trigo y demás insumos necesarios para la producción cervecera; c) comercialización minorista de las materias primas; d) explotación de locales comerciales gastronómicos; e) importación y exportación de las materias primas y cervezas; f) servicios de consultoría, estudios, investigación científica, educación y asesoramiento técnico cervecero. g) Confección, fabricación, producción de todo tipo de bienes vinculados a la gastronomía. h) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'RECUPERACIÓN y TRANSFORMACIÓN de MATERIALES - RECICLADO',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Recolección, recuperación, selección, transformación, acondicionamiento y reciclado de residuos urbanos e industriales; b) Clasificación, lavado, molienda, industrialización y comercialización de los mismos en el mercado. c) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social y en materia de educación ambiental.'
}, {
	title: 'SEMILLAS DE CANNABIS',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados y asociadas, las actividades inherentes a: a) Criar, cultivar, multiplicar, fitomejorar, investigar, procesar, elaborar, almacenar, fraccionar, adquirir, transportar, comercializar y/o desarrollar cualquier otra actividad económica vinculada, conexa y/o complementaria a la producción de plantas madres, plantines, semillas y/o productos derivados; y en general toda actividad amparada por la Ley N° 20.247 de Semillas y Creaciones Fitogenéticas y la que en su futuro la reemplace; b) Diseñar laboratorios, desarrollar técnicas de fitomejoramiento, técnicas de creación de nuevos germoplasmas, sustratos, fertilizantes y/o productos derivados para la nutrición de cultivos; c) Planificar, diseñar, desarrollar, instalar y mantener sistemas de cultivo, abono, acondicionamiento de compost y suelo, siembra, riego, fertirriego, control de plagas, deshumidificación, calefacción, refrigeración, extracción, secado, destilación, fraccionado, empaquetado y cualquier otro proceso de transformación de materias primas e insumos concernientes al objeto social; d) Organizar, dictar y/o participar de capacitaciones, seminarios y/o ferias en espacios públicos y/o privados, así como realizar investigaciones, destinadas al estudio, análisis y divulgación de conocimiento concerniente al objeto social; e) Celebrar convenios, acuerdos y/o contratos con Entidades de la Administración Pública Nacional, provincial y municipal, así como con organismos internacionales, universidades y/o a cualquier otra persona jurídica del derecho público y privado; f) Asesorar técnica y jurídicamente a sus asociados y asociadas en cualquier gestión relacionada con el objeto social.'
}, {
	title: 'TALLER MECÁNICO',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Mecánica y electricidad del automotor común y de avanzada. Rectificación de motores y toda otra tarea relacionada con la mecánica y electrónica del automotor. b) Reparación y mantenimiento de máquinas viales, tractores, aplanadoras, removedores de tierra, motoniveladoras, camiones y todo tipo de maquinaria pesada y liviana. c) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'TECNOLOGÍA, INNOVACIÓN Y CONOCIMIENTO',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) análisis, diseño, desarrollo, soporte técnico, comercialización y distribución de software y hardware. Evaluación y auditoría de soluciones informáticas preexistentes, consultoría en desarrollo de software y cualquier actividad vinculada a las ciencias de la computación. Consultoría y diseño multimedial enfocado a soluciones tecnológicas. Capacitación en desarrollo de software y temas vinculados a la informática. b) Instalación, planificación, dimensionamiento, diseño y mantenimiento de cableado estructurado; c) Mantenimiento, dimensionamiento e instalación integral de software, redes y servidores; desarrollo de herramientas y contenido para capacitación presencial y a distancia; d) Migraciones a software libre; desarrollo e implementación de software y hardware a medida; e) La recuperación de información; la implementación y reparación de bases de datos; diseño y desarrollo de sitios web; f) servicios de diseño gráfico, comercio electrónico y multimedial; g) Diseño e implementación de talleres, capacitaciones presenciales y virtuales de divulgación tecnológica para personas, establecimientos y otras organizaciones de la comunidad; h) importación, compra, distribución y venta, de toda clase de artículos y productos que demande el desarrollo de la actividad educativa. i) gestionar recursos con entidades nacionales y extranjeras, para la promoción de la educación, la cultura, el arte, la ciencia y la tecnología. j) celebrar convenios, acuerdos y/o contratos con entidades públicas y/o privadas y con las entidades territoriales del orden nacional, departamental y/o municipal para el desarrollo de planes, programas y proyectos del objeto social de la cooperativa. k) Compra, venta y fabricación de equipos informáticos y sus componentes. l) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'TELECOMUNICACIONES',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Producción y confección de productos y subproductos inherentes a realizaciones gráficas, audiovisuales, electrónicas y de animación y todo material vinculado a los medios de comunicación audiovisual. b) Realización de eventos vinculados a la comunicación, producciones culturales, y sociales. c) Diseño de papelería comercial y afiches publicitarios. d) Grabaciones, ediciones e impresiones de todo tipo de material periodístico, de investigación, estadísticas y gestión social. e) Obtener licencias, espacios o pautas en los medios de comunicación audiovisual. f) la colocación de productos y subproductos de comunicación audiovisual en el mercado interno e internacional. g) Realización de eventos vinculados a la comunicación, producciones culturales, y sociales. Producir contenidos comunicativos, servicios o bienes culturales, sean audiovisuales, sonoros, fotográficos, textuales o gráficos. h) Producir, distribuir y comercializar bienes culturales y soportes físicos o digitales que permitan la distribución de contenidos, tales como dvd, cd, libros, revistas y/o sitios webs. i) Emitir servicios de comunicación audiovisual, radiofónicos, televisivos y por medios digitales, conforme la normativa que reglamenta su ejercicio. j) producir equipamiento, servicios y asesoramiento técnico para emitir servicios de comunicación audiovisual, radiofónica y otros medios o soportes técnicos de comunicación; k) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'TEXTIL',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) La confección textil industrial en serie, confección de ropa fina, lencería, uniformes, indumentaria deportiva, blanquería, alfombras, tapizado, entramado, confección en cuero, diseño y realización de modelos de temporada, trabajos a medida, bordados, tejidos y todo tipo de accesorios para la indumentaria. b) La confección, producción, elaboración y comercialización de todo tipo de indumentaria con y sin estampado. c) estampados con plancha industrial, plastisol, glitter, sublimados, degrades, papel metalizado, efecto gamuza, entre otros. Estampado técnico con bloqueador textil, sellos, intervenciones, esténcil, entre otros. d) actividades relacionadas con la serigrafía en diseño, impresión, asesoramiento artístico y comercial. e) Sublimado, ploteado, estampado y cualquier otra técnica que posibilite la impresión o el grabado de dibujos, diseños y leyendas sobre telas. f) dictado de cursos, enseñanza de oficio, desfiles y presentaciones.'
}, {
	title: 'TRANSPORTE',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) Transporte de pasajeros, cargas y mercaderías en servicios de corta, media y larga distancia, con servicios comunes punto a punto o ejecutivos puerta a puerta b) Dictado de cursos, capacitaciones y talleres de enseñanza en lo concerniente al objeto social.'
}, {
	title: 'VENTA MINORISTA',
	txt: 'a) Compra, fraccionamiento, envasado y venta minorista de productos de consumo masivo, incluyendo: bebidas y productos alimentarios frescos y procesados, indumentarias comprendidos calzados y bolsos, artículos de limpieza y perfumería, artículos de bazar y juguetería, artículos escolares y de papelería, debiendo desarrollar las actividades conforme a la normativa en vigor. b) Distribución y colocación de los productos en el mercado interno e internacional c) Realizar investigaciones, organizar y/o dictar capacitaciones y/o seminarios y/o educación en espacios públicos y/o privados, en lo concerniente al objeto social.'
}, {
	title: 'VIDRIO',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) la fabricación, producción y colocación de vidrios, b) la industria del vidrio en general, fabricación de envases de vidrio, bazar, vajilla y afines, c) Distribución, comercialización y exportación del producido.'
}, {
	title: 'VIVIENDA',
	txt: 'La Cooperativa tendrá por objeto: a) Adquirir viviendas individuales o colectivas, o construirlas, sea por administración o por medio de contratos con empresas del ramo, para entregarlas en propiedad a los asociados en las condiciones que se especifiquen en el reglamento respectivo; b) Adquirir terrenos para sí o para sus asociados con destino a la vivienda propia; c) Ejecutar por administración o por medio de contratos con terceros las obras necesarias para la conservación, ampliación o mejoramiento de las viviendas de sus asociados; d) Solicitar ante instituciones oficiales o privadas los créditos necesarios para la construcción de la vivienda y gestionarlos en nombre de sus asociados para los mismos fines; e) Adquirir en el mercado los materiales y demás elementos necesarios para la construcción, con destino a su empleo por la cooperativa o al suministro a los asociados; f) Gestionar el concurso de los poderes públicos para la realización de las obras viales necesarias, obras sanitarias y de desagüe en la zona de influencia de la cooperativa; g) Proporcionar a los asociados el asesoramiento en todo lo relacionado con el problema de su vivienda, brindándoles los servicios técnicos y la asistencia jurídica necesaria; h) Propender al fomento de los hábitos de economía y previsión entre los asociados. La Cooperativa excluye de sus objetivos las operaciones de ahorro y préstamo para la vivienda u otros fines; i) Fomentar el espíritu de solidaridad y de ayuda mutua entre los asociados y cumplir con el fin de crear una conciencia cooperativa.'
}, {
	title: 'BICICLETERIA',
	txt: 'La Cooperativa tendrá por objeto: armado, reparación, personalización y mantenimiento de todo tipo de bicicletas; comercialización de repuestos, herramientas y accesorios ; importación de piezas; capacitación y dictado de cursos y talleres. Fomentar el espíritu de solidaridad y de ayuda mutua entre los asociados y cumplir con el fin de crear una conciencia cooperativa.'
}, {
	title: '525-DE PRODUCCIÓN Y TRABAJO - AGROPECUARIO',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) tareas pecuarias, agrícolas, forestales, hortícolas, avícolas, apícolas, piscícolas, ictícolas y destinadas a la obtención de frutos o productos primarios; b) transformación artesanal e industrialización de la materia prima producida por la entidad; c) Dictado de cursos, talleres y seminarios relacionados con el rubro y las actividades de la cooperativa; d) organización y participación en ferias agroganaderas; e) comercialización de los productos de la cooperativa, f) investigacion desarrollo producción y comercialización de tecnologías asociadas a la producción agropecuaria.'
}, {
	title: '525-DE PRODUCCIÓN Y TRABAJO - PESCA ARTESANAL',
	txt: 'La Cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a: a) tareas de pesca y acuicultura; b) transformación artesanal e industrialización de la materia prima producida por la entidad; c) dictado de cursos, talleres y seminarios relacionados con el rubro y las actividades de la cooperativa; d) organización y participación en ferias; e) comercialización y acopio de los productos de la cooperativa; f) venta de los productos de la pesca entregados por los asociados, o de su industrialización y ejecutar todos los actos que tiendan a favorecer la comercialización de la producción, ya sea en estado natural, o previa elaboración industrial; g) otorgar adelantos en dinero a los asociados para operaciones inherentes a sus explotaciones de pesca e industrialización de la misma y a cuenta de los productos entregados o entregar garantizando embarcaciones, elementos de pesca o cualquier otro bien; h) adquirir por cuenta de la cooperativa y proveer a los asociados artículos de consumo y del hogar; i) adquirir para proveer a sus asociados instrumentos, maquinas, motores, combustibles, enseres, maderas, redes y además útiles necesarios para la explotación pesquera o su industrialización; j) instalar usinas o fábricas para la elaboración o transformación de productos; k) proponer el mejoramiento de los sistemas de pesca, adquirir los elementos para ese fin, así también los enseres, útiles y maquinarias que fueren necesarios; l)administrar instalaciones portuarias o bajas náuticas; n) instalar frigoríficos, playas de redes, galpones, almacenes navales y cualquier otra industria útil a la finalidad de la cooperativa.'
}, {
	title: '525-DE PRODUCCIÓN Y TRABAJO - COMERCIALIZADORA',
	txt: 'La cooperativa tendrá por objeto asumir por su propia cuenta, valiéndose del trabajo personal de sus asociados, las actividades inherentes a compra, fraccionamiento, envasado y venta mayorista de productos de consumo masivo, incluyendo bebidas y productos alimentarios frescos y procesados, indumentarias comprendidos calzados y bolsos, artículos de limpieza y perfumería, artículos de bazar y juguetería, artículos escolares y de papelería, debiendo desarrollar las actividades conforme la normativa de rigor.'
}, {
	title: '525-AGROPECUARIA PROVISIÓN DE SERVICIOS AGROPECUARIOS',
	txt: 'La Cooperativa tendrá por objeto: 1. a) La provisión de servicios de labranza; b) de siembra; c) de desmonte, desmalezamiento, limpieza de campos; d) de aplicación de herbicidas, de fertilizantes y otros productos propios del tratamiento de suelos; e) instalación de alambrados, tranqueras, guardaganados; f) parcelamiento de campos; g) provisión de equipos de generación de energía eléctrica, de extracción de agua, de riego, de ordeñe mecánico, de inseminación artificial, de acondicionamiento de productos, de refrigeración de almacenamiento de productos e insumos; h) provisión de servicios de vacunación y de atención veterinaria en general;. i) provisión de semillas, forrajes, herbicidas, fertilizantes y productos veterinarios; j) construcción y mantenimiento de canales de drenaje; k) ejecución de defensas contra plagas y contra granizo; 1) recolección, acondicionamiento, almacenamiento y transporte de la producción agropecuaria. II. A tales fines podrá: a) adquirir, locar o utilizar por cualquier otro título, depósitos, oficinas, galpones, locales, silos, máquinas, aparatos, herramientas y todo inmueble o mueble necesario; b) asesorar técnica y jurídicamente a sus asociados en cualquier gestión relacionada con el giro de sus actividades. III. La Cooperativa fomentará el espíritu de solidaridad entre sus asociados, cumpliendo con el fin de crear una conciencia cooperativa.'
}, {
	title: '525-AGROPECUARIA TRABAJO Y PROVISIÓN DE SERVICIOS AGROPECUARIOS',
	txt: 'La Cooperativa tendrá por objeto en la Sección Provisión de servicios para productores rurales: I. a) La provisión de servicios de labranza; b) de siembra; c) de desmonte, desmalezamiento, limpieza de campos; d) de aplicación de herbicidas, de fertilizantes y otros productos propios del tratamiento de suelos; e) instalación de alambrados, tranqueras, guardaganados; f) parcelamiento de campos; g) provisión de equipos de generación de energía eléctrica, de extracción de agua, de riego, de ordeñe mecánico, de inseminación artificial, de acondicionamiento de productos, de refrigeración de almacenamiento de productos e insumos; h) provisión de servicios de vacunación y de atención veterinaria en general; i) provisión de semillas, forrajes herbicidas, fertilizantes y productos veterinarios; j) construcción y mantenimiento de canales de drenaje; k) ejecución de defensas contra plagas y contra granizo; l) recolección, acondicionamiento, almacenamiento y transporte de la producción agropecuaria; m) provision de equipamentos informaticos, telecomunicaciones y electronicos para la produccion agropecuaria n) asesoramiento en tecnologia agropecuaria . II. A tales fines podrá: a) adquirir, locar o utilizar por cualquier otro título, depósitos, oficinas, galpones, locales, silos, máquinas, aparatos, herramientas y todo inmueble o mueble necesario; b) asesorar técnica y jurídicamente a sus asociados en cualquier gestión relacionada con el giro de sus actividades. III. La Cooperativa fomentará el espíritu de solidaridad entre sus asociados, cumpliendo con el fin de crear una conciencia cooperativa. Sección trabajo: asumir por su propia cuenta, valiendose del trabajo personal de sus asociados, las actividades inherentes a: a) tareas pecuarias, agricolas, forestales, hortícolas, avícolas, apícolas, piscícolas, ictícolas y destinadas a la obtencion de frutos o productos primarios; b) transformacion artesanal e industrializacion de la materia prima producida por la entidad; c) Dictado de cursos, talleres y seminarios relacionados con el rubro y las actividades de la cooperativa; d) organizacion y participacion en ferias agroganaderas; e) comercializacion de los productos de la cooperativa; f) investigacion desarrollo produccion y comercializacion de tecnologias asociadas a la produccion agropecuaria.'
}];