var arrayPartidos = [{cod_prov : 5 , cod_part : 318, name_part : '1 DE MAYO'},
{cod_prov : 5 , cod_part : 151, name_part : '12 DE OCTUBRE'},
{cod_prov : 1 , cod_part : 1, name_part : '25 DE MAYO (BA)'},
{cod_prov : 5 , cod_part : 287, name_part : '25 DE MAYO (CHA)'},
{cod_prov : 13 , cod_part : 431, name_part : '25 DE MAYO (MI)'},
{cod_prov : 15 , cod_part : 456, name_part : '25 DE MAYO (RN)'},
{cod_prov : 17 , cod_part : 476, name_part : '25 DE MAYO (SJ)'},
{cod_prov : 1 , cod_part : 4, name_part : '9 DE JULIO (BA)'},
{cod_prov : 5 , cod_part : 152, name_part : '9 DE JULIO (CHA)'},
{cod_prov : 15 , cod_part : 457, name_part : '9 DE JULIO (RN)'},
{cod_prov : 20 , cod_part : 243, name_part : '9 DE JULIO (SF)'},
{cod_prov : 17 , cod_part : 232, name_part : '9 DE JULIO (SJ)'},
{cod_prov : 1 , cod_part : 5, name_part : 'ADOLFO ALSINA (BA)'},
{cod_prov : 15 , cod_part : 220, name_part : 'ADOLFO ALSINA (RN)'},
{cod_prov : 1 , cod_part : 46, name_part : 'ADOLFO GONZALES CHAVES'},
{cod_prov : 21 , cod_part : 502, name_part : 'AGUIRRE'},
{cod_prov : 17 , cod_part : 479, name_part : 'ALBARDON'},
{cod_prov : 21 , cod_part : 503, name_part : 'ALBERDI'},
{cod_prov : 1 , cod_part : 28, name_part : 'ALBERTI'},
{cod_prov : 1 , cod_part : 6, name_part : 'ALMIRANTE BROWN (BA)'},
{cod_prov : 5 , cod_part : 319, name_part : 'ALMIRANTE BROWN (CHA)'},
{cod_prov : 14 , cod_part : 441, name_part : 'ALUMINE'},
{cod_prov : 2 , cod_part : 370, name_part : 'AMBATO'},
{cod_prov : 2 , cod_part : 371, name_part : 'ANCASTI'},
{cod_prov : 2 , cod_part : 118, name_part : 'ANDALGALA'},
{cod_prov : 14 , cod_part : 442, name_part : 'AÑELO'},
{cod_prov : 17 , cod_part : 480, name_part : 'ANGACO'},
{cod_prov : 16 , cod_part : 463, name_part : 'ANTA'},
{cod_prov : 22 , cod_part : 522, name_part : 'ANTARTIDA'},
{cod_prov : 2 , cod_part : 372, name_part : 'ANTOFAGASTA DE LA SIERRA'},
{cod_prov : 13 , cod_part : 432, name_part : 'APOSTOLES'},
{cod_prov : 11 , cod_part : 410, name_part : 'ARAUCO'},
{cod_prov : 21 , cod_part : 504, name_part : 'ATAMISQUI'},
{cod_prov : 10 , cod_part : 392, name_part : 'ATREUCO'},
{cod_prov : 1 , cod_part : 8, name_part : 'AVELLANEDA (BA)'},
{cod_prov : 15 , cod_part : 290, name_part : 'AVELLANEDA (RN)'},
{cod_prov : 21 , cod_part : 505, name_part : 'AVELLANEDA (SG)'},
{cod_prov : 1 , cod_part : 9, name_part : 'AYACUCHO (BA)'},
{cod_prov : 18 , cod_part : 492, name_part : 'AYACUCHO (SL)'},
{cod_prov : 1 , cod_part : 10, name_part : 'AZUL'},
{cod_prov : 1 , cod_part : 11, name_part : 'BAHIA BLANCA'},
{cod_prov : 1 , cod_part : 12, name_part : 'BALCARCE'},
{cod_prov : 21 , cod_part : 263, name_part : 'BANDA'},
{cod_prov : 1 , cod_part : 13, name_part : 'BARADERO'},
{cod_prov : 15 , cod_part : 221, name_part : 'BARILOCHE'},
{cod_prov : 1 , cod_part : 14, name_part : 'BARTOLOME MITRE'},
{cod_prov : 2 , cod_part : 373, name_part : 'BELEN'},
{cod_prov : 20 , cod_part : 244, name_part : 'BELGRANO (SF)'},
{cod_prov : 21 , cod_part : 506, name_part : 'BELGRANO (SG)'},
{cod_prov : 18 , cod_part : 493, name_part : 'BELGRANO (SL)'},
{cod_prov : 4 , cod_part : 141, name_part : 'BELLA VISTA'},
{cod_prov : 1 , cod_part : 15, name_part : 'BENITO JUAREZ'},
{cod_prov : 1 , cod_part : 16, name_part : 'BERAZATEGUI'},
{cod_prov : 1 , cod_part : 350, name_part : 'BERISSO'},
{cod_prov : 5 , cod_part : 320, name_part : 'BERMEJO (CHA)'},
{cod_prov : 8 , cod_part : 345, name_part : 'BERMEJO (F)'},
{cod_prov : 4 , cod_part : 303, name_part : 'BERON DE ASTRADA'},
{cod_prov : 6 , cod_part : 158, name_part : 'BIEDMA'},
{cod_prov : 1 , cod_part : 17, name_part : 'BOLIVAR'},
{cod_prov : 1 , cod_part : 18, name_part : 'BRAGADO'},
{cod_prov : 21 , cod_part : 507, name_part : 'BRIGADIER JUAN F IBARRA'},
{cod_prov : 23 , cod_part : 284, name_part : 'BURRUYACU'},
{cod_prov : 16 , cod_part : 464, name_part : 'CACHI'},
{cod_prov : 16 , cod_part : 465, name_part : 'CAFAYATE'},
{cod_prov : 13 , cod_part : 433, name_part : 'CAINGUAS'},
{cod_prov : 3 , cod_part : 121, name_part : 'CALAMUCHITA'},
{cod_prov : 10 , cod_part : 393, name_part : 'CALEU CALEU'},
{cod_prov : 17 , cod_part : 481, name_part : 'CALINGASTA'},
{cod_prov : 1 , cod_part : 19, name_part : 'CAMPANA'},
{cod_prov : 13 , cod_part : 285, name_part : 'CANDELARIA'},
{cod_prov : 1 , cod_part : 20, name_part : 'CAÑUELAS'},
{cod_prov : 2 , cod_part : 374, name_part : 'CAPAYAN'},
{cod_prov : 2 , cod_part : 119, name_part : 'CAPITAL (CAT)'},
{cod_prov : 3 , cod_part : 122, name_part : 'CORDOBA'},
{cod_prov : 4 , cod_part : 142, name_part : 'CAPITAL (CTE)'},
{cod_prov : 10 , cod_part : 188, name_part : 'CAPITAL (LP)'},
{cod_prov : 11 , cod_part : 195, name_part : 'CAPITAL (LR)'},
{cod_prov : 13 , cod_part : 214, name_part : 'CAPITAL (MI)'},
{cod_prov : 12 , cod_part : 199, name_part : 'CAPITAL (MZ)'},
{cod_prov : 21 , cod_part : 264, name_part : 'CAPITAL (SG)'},
{cod_prov : 17 , cod_part : 233, name_part : 'CAPITAL (SJ)'},
{cod_prov : 16 , cod_part : 224, name_part : 'CAPITAL (STA)'},
{cod_prov : 23 , cod_part : 271, name_part : 'CAPITAL (TUC)'},
{cod_prov : 1 , cod_part : 21, name_part : 'CAPITAN SARMIENTO'},
{cod_prov : 1 , cod_part : 22, name_part : 'CARLOS CASARES'},
{cod_prov : 1 , cod_part : 292, name_part : 'CARLOS TEJEDOR'},
{cod_prov : 1 , cod_part : 23, name_part : 'CARMEN DE ARECO'},
{cod_prov : 20 , cod_part : 245, name_part : 'CASEROS'},
{cod_prov : 20 , cod_part : 246, name_part : 'CASTELLANOS'},
{cod_prov : 1 , cod_part : 24, name_part : 'CASTELLI'},
{cod_prov : 11 , cod_part : 411, name_part : 'CASTRO BARROS'},
{cod_prov : 14 , cod_part : 443, name_part : 'CATAN LIL'},
{cod_prov : 10 , cod_part : 394, name_part : 'CATRILO'},
{cod_prov : 17 , cod_part : 482, name_part : 'CAUCETE'},
{cod_prov : 16 , cod_part : 225, name_part : 'CERRILLOS'},
{cod_prov : 1 , cod_part : 25, name_part : 'CHACABUCO (BA)'},
{cod_prov : 5 , cod_part : 154, name_part : 'CHACABUCO (CHA)'},
{cod_prov : 18 , cod_part : 494, name_part : 'CHACABUCO (SL)'},
{cod_prov : 10 , cod_part : 395, name_part : 'CHALILEO'},
{cod_prov : 11 , cod_part : 196, name_part : 'CHAMICAL'},
{cod_prov : 10 , cod_part : 396, name_part : 'CHAPALEUFU'},
{cod_prov : 1 , cod_part : 26, name_part : 'CHASCOMUS'},
{cod_prov : 10 , cod_part : 397, name_part : 'CHICAL CO'},
{cod_prov : 23 , cod_part : 272, name_part : 'CHICLIGASTA'},
{cod_prov : 16 , cod_part : 466, name_part : 'CHICOANA'},
{cod_prov : 11 , cod_part : 197, name_part : 'CHILECITO'},
{cod_prov : 17 , cod_part : 234, name_part : 'CHIMBAS'},
{cod_prov : 1 , cod_part : 27, name_part : 'CHIVILCOY'},
{cod_prov : 14 , cod_part : 444, name_part : 'CHOS MALAL'},
{cod_prov : 21 , cod_part : 265, name_part : 'CHOYA'},
{cod_prov : 9 , cod_part : 181, name_part : 'COCHINOCA'},
{cod_prov : 14 , cod_part : 445, name_part : 'COLLON CURA'},
{cod_prov : 1 , cod_part : 33, name_part : 'COLON (BA)'},
{cod_prov : 3 , cod_part : 123, name_part : 'COLON (CBA)'},
{cod_prov : 7 , cod_part : 163, name_part : 'COLON (ER)'},
{cod_prov : 5 , cod_part : 153, name_part : 'COMANDANTE FERNANDEZ'},
{cod_prov : 4 , cod_part : 304, name_part : 'CONCEPCION (CTE)'},
{cod_prov : 13 , cod_part : 434, name_part : 'CONCEPCION (MI)'},
{cod_prov : 7 , cod_part : 164, name_part : 'CONCORDIA'},
{cod_prov : 10 , cod_part : 189, name_part : 'CONESA'},
{cod_prov : 15 , cod_part : 458, name_part : 'CONESA (RN)'},
{cod_prov : 14 , cod_part : 219, name_part : 'CONFLUENCIA'},
{cod_prov : 10 , cod_part : 399, name_part : 'CONHELO'},
{cod_prov : 20 , cod_part : 247, name_part : 'CONSTITUCION'},
{cod_prov : 21 , cod_part : 508, name_part : 'COPO'},
{cod_prov : 1 , cod_part : 34, name_part : 'CORONEL BRANDSEN'},
{cod_prov : 1 , cod_part : 29, name_part : 'CORONEL DORREGO'},
{cod_prov : 11 , cod_part : 412, name_part : 'CORONEL FEL&nbsp'},
{cod_prov : 1 , cod_part : 30, name_part : 'CORONEL PRINGLES (BA)'},
{cod_prov : 18 , cod_part : 495, name_part : 'CORONEL PRINGLES (SL)'},
{cod_prov : 1 , cod_part : 31, name_part : 'CORONEL ROSALES'},
{cod_prov : 1 , cod_part : 32, name_part : 'CORONEL SUAREZ'},
{cod_prov : 19 , cod_part : 239, name_part : 'CORPEN AIKE'},
{cod_prov : 23 , cod_part : 273, name_part : 'CRUZ ALTA'},
{cod_prov : 3 , cod_part : 125, name_part : 'CRUZ DEL EJE'},
{cod_prov : 10 , cod_part : 400, name_part : 'CURACO'},
{cod_prov : 4 , cod_part : 143, name_part : 'CURUZU CUATIA'},
{cod_prov : 6 , cod_part : 333, name_part : 'CUSHAMEN'},
{cod_prov : 1 , cod_part : 35, name_part : 'DAIREAUX'},
{cod_prov : 1 , cod_part : 36, name_part : 'DE LA COSTA'},
{cod_prov : 19 , cod_part : 240, name_part : 'DESEADO'},
{cod_prov : 7 , cod_part : 165, name_part : 'DIAMANTE'},
{cod_prov : 1 , cod_part : 37, name_part : 'DOLORES'},
{cod_prov : 9 , cod_part : 182, name_part : 'DR MANUEL BELGRANO'},
{cod_prov : 2 , cod_part : 375, name_part : 'EL ALTO'},
{cod_prov : 9 , cod_part : 183, name_part : 'EL CARMEN'},
{cod_prov : 15 , cod_part : 459, name_part : 'EL CUY'},
{cod_prov : 13 , cod_part : 215, name_part : 'EL DORADO'},
{cod_prov : 4 , cod_part : 144, name_part : 'EMPEDRADO'},
{cod_prov : 1 , cod_part : 38, name_part : 'ENSENADA'},
{cod_prov : 6 , cod_part : 159, name_part : 'ESCALANTE'},
{cod_prov : 1 , cod_part : 39, name_part : 'ESCOBAR'},
{cod_prov : 4 , cod_part : 145, name_part : 'ESQUINA'},
{cod_prov : 1 , cod_part : 40, name_part : 'ESTEBAN ECHEVERRIA'},
{cod_prov : 1 , cod_part : 351, name_part : 'EXALTACION DE LA CRUZ'},
{cod_prov : 1 , cod_part : 41, name_part : 'EZEIZA'},
{cod_prov : 23 , cod_part : 274, name_part : 'FAMAILLA'},
{cod_prov : 11 , cod_part : 413, name_part : 'FAMATINA'},
{cod_prov : 7 , cod_part : 166, name_part : 'FEDERACION'},
{cod_prov : 7 , cod_part : 167, name_part : 'FEDERAL'},
{cod_prov : 7 , cod_part : 343, name_part : 'FELICIANO'},
{cod_prov : 21 , cod_part : 509, name_part : 'FIGUEROA'},
{cod_prov : 1 , cod_part : 42, name_part : 'FLORENCIO VARELA'},
{cod_prov : 1 , cod_part : 7, name_part : 'FLORENTINO AMEGHINO (BA)'},
{cod_prov : 6 , cod_part : 334, name_part : 'FLORENTINO AMEGHINO (CHU)'},
{cod_prov : 8 , cod_part : 177, name_part : 'FORMOSA'},
{cod_prov : 5 , cod_part : 321, name_part : 'FRAY JUSTO SANTA MARIA DE ORO'},
{cod_prov : 2 , cod_part : 376, name_part : 'FRAY MAMERTO ESQUIU'},
{cod_prov : 6 , cod_part : 160, name_part : 'FUTALEUFU'},
{cod_prov : 6 , cod_part : 161, name_part : 'GAIMAN'},
{cod_prov : 20 , cod_part : 293, name_part : 'GARAY'},
{cod_prov : 6 , cod_part : 335, name_part : 'GASTRE'},
{cod_prov : 1 , cod_part : 47, name_part : 'GENERAL ALVARADO'},
{cod_prov : 1 , cod_part : 352, name_part : 'GENERAL ALVEAR (BA)'},
{cod_prov : 4 , cod_part : 305, name_part : 'GENERAL ALVEAR (CTE)'},
{cod_prov : 12 , cod_part : 201, name_part : 'GENERAL ALVEAR (MZ)'},
{cod_prov : 11 , cod_part : 414, name_part : 'GENERAL ANGEL VICENTE PEÑALOZA'},
{cod_prov : 1 , cod_part : 43, name_part : 'GENERAL ARENALES'},
{cod_prov : 1 , cod_part : 353, name_part : 'GENERAL BELGRANO (BA)'},
{cod_prov : 5 , cod_part : 155, name_part : 'GENERAL BELGRANO (CHA)'},
{cod_prov : 11 , cod_part : 415, name_part : 'GENERAL BELGRANO (LR)'},
{cod_prov : 5 , cod_part : 294, name_part : 'GENERAL DONOVAN'},
{cod_prov : 5 , cod_part : 322, name_part : 'GENERAL GUEMES'},
{cod_prov : 1 , cod_part : 354, name_part : 'GENERAL GUIDO'},
{cod_prov : 16 , cod_part : 227, name_part : 'GENERAL JOSE DE SAN MARTIN'},
{cod_prov : 11 , cod_part : 416, name_part : 'GENERAL JUAN FACUNDO QUIROGA'},
{cod_prov : 1 , cod_part : 355, name_part : 'GENERAL LAMADRID (BA)'},
{cod_prov : 11 , cod_part : 417, name_part : 'GENERAL LAMADRID (LR)'},
{cod_prov : 1 , cod_part : 356, name_part : 'GENERAL LAS HERAS'},
{cod_prov : 1 , cod_part : 357, name_part : 'GENERAL LAVALLE'},
{cod_prov : 20 , cod_part : 249, name_part : 'GENERAL LOPEZ'},
{cod_prov : 1 , cod_part : 44, name_part : 'GENERAL MADARIAGA'},
{cod_prov : 13 , cod_part : 438, name_part : 'GENERAL MANUEL BELGRANO (MN)'},
{cod_prov : 16 , cod_part : 226, name_part : 'GENERAL MARTIN M GUEMES (SAL)'},
{cod_prov : 20 , cod_part : 251, name_part : 'GENERAL OBLIGADO'},
{cod_prov : 11 , cod_part : 198, name_part : 'GENERAL OCAMPO'},
{cod_prov : 1 , cod_part : 358, name_part : 'GENERAL PAZ (BA)'},
{cod_prov : 4 , cod_part : 306, name_part : 'GENERAL PAZ (CTE)'},
{cod_prov : 18 , cod_part : 237, name_part : 'GENERAL PEDERNERA'},
{cod_prov : 1 , cod_part : 49, name_part : 'GENERAL PINTO'},
{cod_prov : 1 , cod_part : 50, name_part : 'GENERAL PUEYRREDON'},
{cod_prov : 3 , cod_part : 295, name_part : 'GENERAL ROCA (CBA)'},
{cod_prov : 15 , cod_part : 222, name_part : 'GENERAL ROCA (RN)'},
{cod_prov : 1 , cod_part : 51, name_part : 'GENERAL RODRIGUEZ'},
{cod_prov : 1 , cod_part : 52, name_part : 'GENERAL SAN MARTIN (BA)'},
{cod_prov : 3 , cod_part : 126, name_part : 'GENERAL SAN MARTIN (CBA)'},
{cod_prov : 11 , cod_part : 418, name_part : 'GENERAL SAN MARTIN (LR)'},
{cod_prov : 21 , cod_part : 510, name_part : 'GENERAL SAN MARTIN (SG)'},
{cod_prov : 11 , cod_part : 419, name_part : 'GENERAL SARMIENTO'},
{cod_prov : 21 , cod_part : 266, name_part : 'GENERAL TABOADA'},
{cod_prov : 1 , cod_part : 54, name_part : 'GENERAL VIAMONTE'},
{cod_prov : 1 , cod_part : 45, name_part : 'GENERAL VILLEGAS'},
{cod_prov : 18 , cod_part : 496, name_part : 'GOBERNADOR DUPUY'},
{cod_prov : 11 , cod_part : 420, name_part : 'GOBERNADOR GORDILLO'},
{cod_prov : 12 , cod_part : 200, name_part : 'GODOY CRUZ'},
{cod_prov : 4 , cod_part : 146, name_part : 'GOYA'},
{cod_prov : 23 , cod_part : 524, name_part : 'GRANEROS'},
{cod_prov : 16 , cod_part : 467, name_part : 'GUACHIPAS'},
{cod_prov : 7 , cod_part : 168, name_part : 'GUALEGUAY'},
{cod_prov : 7 , cod_part : 169, name_part : 'GUALEGUAYCHU'},
{cod_prov : 1 , cod_part : 56, name_part : 'GUAMINI'},
{cod_prov : 13 , cod_part : 439, name_part : 'GUARANI'},
{cod_prov : 21 , cod_part : 511, name_part : 'GUASAYAN'},
{cod_prov : 10 , cod_part : 190, name_part : 'GUATRACHE'},
{cod_prov : 12 , cod_part : 202, name_part : 'GUAYMALLEN'},
{cod_prov : 19 , cod_part : 241, name_part : 'GUER AIKE'},
{cod_prov : 1 , cod_part : 57, name_part : 'HIPOLITO YRIGOYEN'},
{cod_prov : 10 , cod_part : 401, name_part : 'HUCAL'},
{cod_prov : 14 , cod_part : 446, name_part : 'HUILICHES'},
{cod_prov : 9 , cod_part : 383, name_part : 'HUMAHUACA'},
{cod_prov : 1 , cod_part : 58, name_part : 'HURLINGHAM'},
{cod_prov : 17 , cod_part : 483, name_part : 'IGLESIA'},
{cod_prov : 13 , cod_part : 440, name_part : 'IGUAZU'},
{cod_prov : 5 , cod_part : 323, name_part : 'INDEPENDENCIA (CHA)'},
{cod_prov : 11 , cod_part : 421, name_part : 'INDEPENDENCIA (LR)'},
{cod_prov : 20 , cod_part : 252, name_part : 'IRIONDO'},
{cod_prov : 16 , cod_part : 468, name_part : 'IRUYA'},
{cod_prov : 3 , cod_part : 127, name_part : 'ISCHILIN'},
{cod_prov : 7 , cod_part : 344, name_part : 'ISLAS DEL IBICUY'},
{cod_prov : 4 , cod_part : 307, name_part : 'ITATI'},
{cod_prov : 1 , cod_part : 59, name_part : 'ITUZAINGO (BA)'},
{cod_prov : 4 , cod_part : 147, name_part : 'ITUZAINGO (CTE)'},
{cod_prov : 17 , cod_part : 484, name_part : 'JACHAL'},
{cod_prov : 21 , cod_part : 512, name_part : 'JIMENEZ'},
{cod_prov : 1 , cod_part : 60, name_part : 'JOSE CLEMENTE PAZ'},
{cod_prov : 23 , cod_part : 275, name_part : 'JUAN B ALBERDI'},
{cod_prov : 3 , cod_part : 128, name_part : 'JUAREZ CELMAN'},
{cod_prov : 1 , cod_part : 61, name_part : 'JUNIN (BA)'},
{cod_prov : 12 , cod_part : 203, name_part : 'JUNIN (MZ)'},
{cod_prov : 18 , cod_part : 497, name_part : 'JUNIN (SL)'},
{cod_prov : 16 , cod_part : 469, name_part : 'LA CALDERA'},
{cod_prov : 16 , cod_part : 470, name_part : 'LA CANDELARIA'},
{cod_prov : 20 , cod_part : 253, name_part : 'LA CAPITAL (SF)'},
{cod_prov : 18 , cod_part : 238, name_part : 'JUAN MARTIN DE PUEYRREDON'},
{cod_prov : 23 , cod_part : 525, name_part : 'LA COCHA'},
{cod_prov : 1 , cod_part : 62, name_part : 'LA MATANZA'},
{cod_prov : 2 , cod_part : 377, name_part : 'LA PAZ (CAT)'},
{cod_prov : 7 , cod_part : 170, name_part : 'LA PAZ (ER)'},
{cod_prov : 12 , cod_part : 426, name_part : 'LA PAZ (MZ)'},
{cod_prov : 1 , cod_part : 63, name_part : 'LA PLATA'},
{cod_prov : 16 , cod_part : 471, name_part : 'LA POMA'},
{cod_prov : 16 , cod_part : 472, name_part : 'LA VIÑA'},
{cod_prov : 14 , cod_part : 447, name_part : 'LACAR'},
{cod_prov : 19 , cod_part : 499, name_part : 'LAGO ARGENTINO'},
{cod_prov : 19 , cod_part : 500, name_part : 'LAGO BUENOS AIRES'},
{cod_prov : 8 , cod_part : 346, name_part : 'LAISHI'},
{cod_prov : 6 , cod_part : 336, name_part : 'LANGUIÑEO'},
{cod_prov : 1 , cod_part : 64, name_part : 'LANUS'},
{cod_prov : 1 , cod_part : 359, name_part : 'LAPRIDA'},
{cod_prov : 20 , cod_part : 254, name_part : 'LAS COLONIAS'},
{cod_prov : 1 , cod_part : 65, name_part : 'LAS FLORES'},
{cod_prov : 12 , cod_part : 204, name_part : 'LAS HERAS'},
{cod_prov : 4 , cod_part : 308, name_part : 'LAVALLE (CTE)'},
{cod_prov : 12 , cod_part : 427, name_part : 'LAVALLE (MZ)'},
{cod_prov : 23 , cod_part : 283, name_part : 'LEALES'},
{cod_prov : 1 , cod_part : 66, name_part : 'LEANDRO N. ALEM (BA)'},
{cod_prov : 13 , cod_part : 216, name_part : 'LEANDRO N. ALEM (MN)'},
{cod_prov : 9 , cod_part : 184, name_part : 'LEDESMA'},
{cod_prov : 5 , cod_part : 324, name_part : 'LIBERTAD'},
{cod_prov : 5 , cod_part : 325, name_part : 'LIBERTADOR GRAL SAN MARTIN(CHA'},
{cod_prov : 13 , cod_part : 286, name_part : 'LIBERTADOR GRAL SAN MARTIN(MI)'},
{cod_prov : 18 , cod_part : 498, name_part : 'LIBERTADOR GRAL SAN MARTIN(SL)'},
{cod_prov : 10 , cod_part : 402, name_part : 'LIHUEL CALEL'},
{cod_prov : 10 , cod_part : 403, name_part : 'LIMAY MAHUIDA'},
{cod_prov : 1 , cod_part : 67, name_part : 'LINCOLN'},
{cod_prov : 1 , cod_part : 68, name_part : 'LOBERIA'},
{cod_prov : 1 , cod_part : 69, name_part : 'LOBOS'},
{cod_prov : 1 , cod_part : 70, name_part : 'LOMAS DE ZAMORA'},
{cod_prov : 14 , cod_part : 448, name_part : 'LONCOPUE'},
{cod_prov : 21 , cod_part : 513, name_part : 'LORETO'},
{cod_prov : 16 , cod_part : 473, name_part : 'LOS ANDES'},
{cod_prov : 14 , cod_part : 449, name_part : 'LOS LAGOS'},
{cod_prov : 10 , cod_part : 404, name_part : 'LOVENTUE'},
{cod_prov : 1 , cod_part : 71, name_part : 'LUJAN'},
{cod_prov : 12 , cod_part : 206, name_part : 'LUJAN DE CUYO'},
{cod_prov : 23 , cod_part : 276, name_part : 'LULES'},
{cod_prov : 19 , cod_part : 242, name_part : 'MAGALLANES'},
{cod_prov : 1 , cod_part : 72, name_part : 'MAGDALENA'},
{cod_prov : 1 , cod_part : 73, name_part : 'MAIPU (BA)'},
{cod_prov : 5 , cod_part : 326, name_part : 'MAIPU (CHA)'},
{cod_prov : 12 , cod_part : 207, name_part : 'MAIPU (MZ)'},
{cod_prov : 12 , cod_part : 208, name_part : 'MALARGUE'},
{cod_prov : 22 , cod_part : 523, name_part : 'MALVINAS (TF)'},
{cod_prov : 1 , cod_part : 74, name_part : 'MALVINAS ARGENTINAS'},
{cod_prov : 1 , cod_part : 75, name_part : 'MAR CHIQUITA'},
{cod_prov : 10 , cod_part : 191, name_part : 'MARACO'},
{cod_prov : 3 , cod_part : 129, name_part : 'MARCOS JUAREZ'},
{cod_prov : 1 , cod_part : 76, name_part : 'MARCOS PAZ'},
{cod_prov : 6 , cod_part : 337, name_part : 'MARTIRES'},
{cod_prov : 8 , cod_part : 347, name_part : 'MATACOS'},
{cod_prov : 5 , cod_part : 156, name_part : 'MAYOR LUIS J FONTANA'},
{cod_prov : 4 , cod_part : 309, name_part : 'MBURUCUYA'},
{cod_prov : 1 , cod_part : 77, name_part : 'MERCEDES (BA)'},
{cod_prov : 4 , cod_part : 148, name_part : 'MERCEDES (CTS)'},
{cod_prov : 1 , cod_part : 78, name_part : 'MERLO'},
{cod_prov : 16 , cod_part : 228, name_part : 'METAN'},
{cod_prov : 3 , cod_part : 297, name_part : 'MINAS (CBA)'},
{cod_prov : 14 , cod_part : 450, name_part : 'MINAS (N)'},
{cod_prov : 21 , cod_part : 514, name_part : 'MITRE'},
{cod_prov : 16 , cod_part : 474, name_part : 'MOLINOS'},
{cod_prov : 1 , cod_part : 106, name_part : 'MONTE'},
{cod_prov : 4 , cod_part : 149, name_part : 'MONTE CASEROS'},
{cod_prov : 1 , cod_part : 360, name_part : 'MONTE HERMOSO'},
{cod_prov : 13 , cod_part : 217, name_part : 'MONTECARLO'},
{cod_prov : 23 , cod_part : 277, name_part : 'MONTEROS'},
{cod_prov : 1 , cod_part : 79, name_part : 'MORENO (BA)'},
{cod_prov : 21 , cod_part : 515, name_part : 'MORENO (SGO)'},
{cod_prov : 1 , cod_part : 80, name_part : 'MORON'},
{cod_prov : 1 , cod_part : 81, name_part : 'NAVARRO'},
{cod_prov : 1 , cod_part : 82, name_part : 'NECOCHEA'},
{cod_prov : 7 , cod_part : 171, name_part : 'NOGOYA'},
{cod_prov : 14 , cod_part : 455, name_part : 'ÑORQUIN'},
{cod_prov : 15 , cod_part : 462, name_part : 'ÑORQUINCO'},
{cod_prov : 5 , cod_part : 327, name_part : 'O HIGGINS'},
{cod_prov : 13 , cod_part : 218, name_part : 'OBERA'},
{cod_prov : 21 , cod_part : 516, name_part : 'OJO DE AGUA'},
{cod_prov : 1 , cod_part : 83, name_part : 'OLAVARRIA'},
{cod_prov : 16 , cod_part : 229, name_part : 'ORAN'},
{cod_prov : 2 , cod_part : 378, name_part : 'PACLIN'},
{cod_prov : 9 , cod_part : 185, name_part : 'PALPALA'},
{cod_prov : 7 , cod_part : 172, name_part : 'PARANA'},
{cod_prov : 6 , cod_part : 338, name_part : 'PASO DE INDIOS'},
{cod_prov : 4 , cod_part : 150, name_part : 'PASO DE LOS LIBRES'},
{cod_prov : 1 , cod_part : 84, name_part : 'PATAGONES'},
{cod_prov : 8 , cod_part : 178, name_part : 'PATIÑO'},
{cod_prov : 1 , cod_part : 85, name_part : 'PEHUAJO'},
{cod_prov : 14 , cod_part : 451, name_part : 'PEHUENCHES'},
{cod_prov : 1 , cod_part : 86, name_part : 'PELLEGRINI (BA)'},
{cod_prov : 21 , cod_part : 267, name_part : 'PELLEGRINI (SG)'},
{cod_prov : 1 , cod_part : 87, name_part : 'PERGAMINO'},
{cod_prov : 15 , cod_part : 289, name_part : 'PICHI MAHUIDA'},
{cod_prov : 14 , cod_part : 452, name_part : 'PICUN LEUFU'},
{cod_prov : 14 , cod_part : 453, name_part : 'PICUNCHES'},
{cod_prov : 1 , cod_part : 361, name_part : 'PILA'},
{cod_prov : 8 , cod_part : 348, name_part : 'PILAGAS'},
{cod_prov : 1 , cod_part : 88, name_part : 'PILAR'},
{cod_prov : 15 , cod_part : 460, name_part : 'PILCANIYEU'},
{cod_prov : 8 , cod_part : 179, name_part : 'PILCOMAYO'},
{cod_prov : 1 , cod_part : 362, name_part : 'PINAMAR'},
{cod_prov : 8 , cod_part : 180, name_part : 'PIRANE'},
{cod_prov : 3 , cod_part : 298, name_part : 'POCHO'},
{cod_prov : 17 , cod_part : 485, name_part : 'POCITO'},
{cod_prov : 2 , cod_part : 379, name_part : 'POMAN'},
{cod_prov : 5 , cod_part : 328, name_part : 'PRESIDENTE DE LA PLAZA'},
{cod_prov : 1 , cod_part : 89, name_part : 'PRESIDENTE PERON'},
{cod_prov : 3 , cod_part : 135, name_part : 'PRESIDENTE ROQUE SAENZ PEÑA'},
{cod_prov : 1 , cod_part : 90, name_part : 'PUAN'},
{cod_prov : 10 , cod_part : 405, name_part : 'PUELEN'},
{cod_prov : 3 , cod_part : 131, name_part : 'PUNILLA'},
{cod_prov : 1 , cod_part : 91, name_part : 'PUNTA INDIO'},
{cod_prov : 21 , cod_part : 517, name_part : 'QUEBRACHOS'},
{cod_prov : 10 , cod_part : 406, name_part : 'QUEMU QUEMU'},
{cod_prov : 1 , cod_part : 92, name_part : 'QUILMES'},
{cod_prov : 5 , cod_part : 329, name_part : 'QUITILIPI'},
{cod_prov : 1 , cod_part : 93, name_part : 'RAMALLO'},
{cod_prov : 8 , cod_part : 349, name_part : 'RAMON LISTA'},
{cod_prov : 10 , cod_part : 407, name_part : 'RANCUL'},
{cod_prov : 1 , cod_part : 94, name_part : 'RAUCH'},
{cod_prov : 6 , cod_part : 162, name_part : 'RAWSON'},
{cod_prov : 17 , cod_part : 486, name_part : 'RAWSON (SJ)'},
{cod_prov : 10 , cod_part : 192, name_part : 'REALICO'},
{cod_prov : 9 , cod_part : 384, name_part : 'RINCONADA'},
{cod_prov : 19 , cod_part : 501, name_part : 'RIO CHICO (SC)'},
{cod_prov : 23 , cod_part : 278, name_part : 'RIO CHICO (TU)'},
{cod_prov : 3 , cod_part : 132, name_part : 'RIO CUARTO'},
{cod_prov : 22 , cod_part : 269, name_part : 'RIO GRANDE'},
{cod_prov : 21 , cod_part : 518, name_part : 'RIO HONDO'},
{cod_prov : 3 , cod_part : 133, name_part : 'RIO PRIMERO'},
{cod_prov : 3 , cod_part : 296, name_part : 'RIO SECO'},
{cod_prov : 3 , cod_part : 134, name_part : 'RIO SEGUNDO'},
{cod_prov : 6 , cod_part : 339, name_part : 'RIO SENGUER'},
{cod_prov : 1 , cod_part : 363, name_part : 'RIVADAVIA (BA)'},
{cod_prov : 12 , cod_part : 210, name_part : 'RIVADAVIA (Mz)'},
{cod_prov : 21 , cod_part : 519, name_part : 'RIVADAVIA (Sg)'},
{cod_prov : 17 , cod_part : 235, name_part : 'RIVADAVIA (SJ)'},
{cod_prov : 16 , cod_part : 475, name_part : 'RIVADAVIA (Sta)'},
{cod_prov : 21 , cod_part : 268, name_part : 'ROBLES'},
{cod_prov : 1 , cod_part : 95, name_part : 'ROJAS'},
{cod_prov : 1 , cod_part : 364, name_part : 'ROQUE PEREZ'},
{cod_prov : 20 , cod_part : 255, name_part : 'ROSARIO'},
{cod_prov : 16 , cod_part : 230, name_part : 'ROSARIO DE LA FRONTERA'},
{cod_prov : 16 , cod_part : 231, name_part : 'ROSARIO DE LERMA'},
{cod_prov : 11 , cod_part : 422, name_part : 'ROSARIO VERA PEÑALOZA'},
{cod_prov : 1 , cod_part : 96, name_part : 'SAAVEDRA'},
{cod_prov : 4 , cod_part : 310, name_part : 'SALADAS'},
{cod_prov : 1 , cod_part : 97, name_part : 'SALADILLO'},
{cod_prov : 21 , cod_part : 250, name_part : 'SALAVINA'},
{cod_prov : 1 , cod_part : 98, name_part : 'SALLIQUELO'},
{cod_prov : 1 , cod_part : 99, name_part : 'SALTO'},
{cod_prov : 3 , cod_part : 299, name_part : 'SAN ALBERTO'},
{cod_prov : 1 , cod_part : 101, name_part : 'SAN ANDRES DE GILES'},
{cod_prov : 9 , cod_part : 385, name_part : 'SAN ANTONIO (J)'},
{cod_prov : 15 , cod_part : 223, name_part : 'SAN ANTONIO (RN)'},
{cod_prov : 1 , cod_part : 102, name_part : 'SAN ANTONIO DE ARECO'},
{cod_prov : 11 , cod_part : 423, name_part : 'SAN BLAS DE LOS SAUCES'},
{cod_prov : 12 , cod_part : 428, name_part : 'SAN CARLOS (MZ)'},
{cod_prov : 16 , cod_part : 477, name_part : 'SAN CARLOS (STA)'},
{cod_prov : 1 , cod_part : 366, name_part : 'SAN CAYETANO'},
{cod_prov : 4 , cod_part : 311, name_part : 'SAN COSME'},
{cod_prov : 20 , cod_part : 256, name_part : 'SAN CRISTOBAL'},
{cod_prov : 1 , cod_part : 103, name_part : 'SAN FERNANDO (BA)'},
{cod_prov : 5 , cod_part : 157, name_part : 'SAN FERNANDO (CHA)'},
{cod_prov : 13 , cod_part : 291, name_part : 'SAN IGNACIO'},
{cod_prov : 1 , cod_part : 104, name_part : 'SAN ISIDRO'},
{cod_prov : 3 , cod_part : 136, name_part : 'SAN JAVIER (CBA)'},
{cod_prov : 13 , cod_part : 436, name_part : 'SAN JAVIER (MI)'},
{cod_prov : 20 , cod_part : 257, name_part : 'SAN JAVIER (SF)'},
{cod_prov : 20 , cod_part : 258, name_part : 'SAN JERONIMO'},
{cod_prov : 3 , cod_part : 137, name_part : 'SAN JUSTO (CBA)'},
{cod_prov : 20 , cod_part : 259, name_part : 'SAN JUSTO (SF)'},
{cod_prov : 5 , cod_part : 330, name_part : 'SAN LORENZO (CH)'},
{cod_prov : 20 , cod_part : 260, name_part : 'SAN LORENZO (SF)'},
{cod_prov : 4 , cod_part : 312, name_part : 'SAN LUIS DEL PALMAR'},
{cod_prov : 4 , cod_part : 313, name_part : 'SAN MARTIN (CTE)'},
{cod_prov : 12 , cod_part : 211, name_part : 'SAN MARTIN (MZ)'},
{cod_prov : 20 , cod_part : 261, name_part : 'SAN MARTIN (SF)'},
{cod_prov : 17 , cod_part : 487, name_part : 'SAN MARTIN (SJ)'},
{cod_prov : 1 , cod_part : 105, name_part : 'SAN MIGUEL (BA)'},
{cod_prov : 4 , cod_part : 314, name_part : 'SAN MIGUEL (CTE)'},
{cod_prov : 1 , cod_part : 107, name_part : 'SAN NICOLAS'},
{cod_prov : 1 , cod_part : 108, name_part : 'SAN PEDRO (BA)'},
{cod_prov : 9 , cod_part : 186, name_part : 'SAN PEDRO (J)'},
{cod_prov : 13 , cod_part : 437, name_part : 'SAN PEDRO (MI)'},
{cod_prov : 12 , cod_part : 212, name_part : 'SAN RAFAEL'},
{cod_prov : 4 , cod_part : 315, name_part : 'SAN ROQUE'},
{cod_prov : 1 , cod_part : 109, name_part : 'SAN VICENTE'},
{cod_prov : 11 , cod_part : 424, name_part : 'SANAGASTA'},
{cod_prov : 9 , cod_part : 386, name_part : 'SANTA BARBARA'},
{cod_prov : 9 , cod_part : 387, name_part : 'SANTA CATALINA'},
{cod_prov : 17 , cod_part : 236, name_part : 'SANTA LUCIA'},
{cod_prov : 2 , cod_part : 380, name_part : 'SANTA MARIA (CAT)'},
{cod_prov : 3 , cod_part : 138, name_part : 'SANTA MARIA (CBA)'},
{cod_prov : 2 , cod_part : 381, name_part : 'SANTA ROSA (CAT)'},
{cod_prov : 12 , cod_part : 429, name_part : 'SANTA ROSA (MZ)'},
{cod_prov : 16 , cod_part : 478, name_part : 'SANTA VICTORIA'},
{cod_prov : 4 , cod_part : 316, name_part : 'SANTO TOME'},
{cod_prov : 5 , cod_part : 331, name_part : 'SARGENTO CABRAL'},
{cod_prov : 6 , cod_part : 340, name_part : 'SARMIENTO (CHU)'},
{cod_prov : 21 , cod_part : 520, name_part : 'SARMIENTO (SG)'},
{cod_prov : 17 , cod_part : 488, name_part : 'SARMIENTO (SJ)'},
{cod_prov : 4 , cod_part : 317, name_part : 'SAUCE'},
{cod_prov : 21 , cod_part : 521, name_part : 'SILIPICA'},
{cod_prov : 23 , cod_part : 526, name_part : 'SIMOCA'},
{cod_prov : 1 , cod_part : 901, name_part : 'SIN DEPARTAMENTO (01)'},
{cod_prov : 2 , cod_part : 902, name_part : 'SIN DEPARTAMENTO (02)'},
{cod_prov : 3 , cod_part : 903, name_part : 'SIN DEPARTAMENTO (03)'},
{cod_prov : 4 , cod_part : 904, name_part : 'SIN DEPARTAMENTO (04)'},
{cod_prov : 5 , cod_part : 905, name_part : 'SIN DEPARTAMENTO (05)'},
{cod_prov : 6 , cod_part : 906, name_part : 'SIN DEPARTAMENTO (06)'},
{cod_prov : 7 , cod_part : 907, name_part : 'SIN DEPARTAMENTO (07)'},
{cod_prov : 8 , cod_part : 908, name_part : 'SIN DEPARTAMENTO (08)'},
{cod_prov : 9 , cod_part : 909, name_part : 'SIN DEPARTAMENTO (09)'},
{cod_prov : 10 , cod_part : 910, name_part : 'SIN DEPARTAMENTO (10)'},
{cod_prov : 11 , cod_part : 911, name_part : 'SIN DEPARTAMENTO (11)'},
{cod_prov : 12 , cod_part : 912, name_part : 'SIN DEPARTAMENTO (12)'},
{cod_prov : 13 , cod_part : 913, name_part : 'SIN DEPARTAMENTO (13)'},
{cod_prov : 14 , cod_part : 914, name_part : 'SIN DEPARTAMENTO (14)'},
{cod_prov : 15 , cod_part : 915, name_part : 'SIN DEPARTAMENTO (15)'},
{cod_prov : 16 , cod_part : 916, name_part : 'SIN DEPARTAMENTO (16)'},
{cod_prov : 17 , cod_part : 917, name_part : 'SIN DEPARTAMENTO (17)'},
{cod_prov : 18 , cod_part : 918, name_part : 'SIN DEPARTAMENTO (18)'},
{cod_prov : 19 , cod_part : 919, name_part : 'SIN DEPARTAMENTO (19)'},
{cod_prov : 20 , cod_part : 920, name_part : 'SIN DEPARTAMENTO (20)'},
{cod_prov : 21 , cod_part : 921, name_part : 'SIN DEPARTAMENTO (21)'},
{cod_prov : 23 , cod_part : 923, name_part : 'SIN DEPARTAMENTO (23)'},
{cod_prov : 3 , cod_part : 300, name_part : 'SOBREMONTE'},
{cod_prov : 1 , cod_part : 110, name_part : 'SUIPACHA'},
{cod_prov : 9 , cod_part : 388, name_part : 'SUSQUES'},
{cod_prov : 23 , cod_part : 279, name_part : 'TAFI'},
{cod_prov : 23 , cod_part : 527, name_part : 'TAFI DEL VALLE'},
{cod_prov : 23 , cod_part : 280, name_part : 'TAFI VIEJO'},
{cod_prov : 7 , cod_part : 173, name_part : 'TALA'},
{cod_prov : 1 , cod_part : 111, name_part : 'TANDIL'},
{cod_prov : 1 , cod_part : 112, name_part : 'TAPALQUE'},
{cod_prov : 5 , cod_part : 332, name_part : 'TAPENAGA'},
{cod_prov : 6 , cod_part : 341, name_part : 'TEHUELCHES'},
{cod_prov : 6 , cod_part : 342, name_part : 'TELSEN'},
{cod_prov : 3 , cod_part : 139, name_part : 'TERCERO ARRIBA'},
{cod_prov : 1 , cod_part : 113, name_part : 'TIGRE'},
{cod_prov : 9 , cod_part : 389, name_part : 'TILCARA'},
{cod_prov : 2 , cod_part : 120, name_part : 'TINOGASTA'},
{cod_prov : 10 , cod_part : 193, name_part : 'TOAY'},
{cod_prov : 1 , cod_part : 367, name_part : 'TORDILLO'},
{cod_prov : 1 , cod_part : 368, name_part : 'TORNQUIST'},
{cod_prov : 3 , cod_part : 301, name_part : 'TOTORAL'},
{cod_prov : 23 , cod_part : 282, name_part : 'TRANCAS'},
{cod_prov : 10 , cod_part : 408, name_part : 'TRENEL'},
{cod_prov : 1 , cod_part : 114, name_part : 'TRENQUE LAUQUEN'},
{cod_prov : 1 , cod_part : 2, name_part : 'TRES ARROYOS'},
{cod_prov : 1 , cod_part : 3, name_part : 'TRES DE FEBRERO'},
{cod_prov : 1 , cod_part : 369, name_part : 'TRES LOMAS'},
{cod_prov : 3 , cod_part : 302, name_part : 'TULUMBA'},
{cod_prov : 9 , cod_part : 390, name_part : 'TUMBAYA'},
{cod_prov : 12 , cod_part : 213, name_part : 'TUNUYAN'},
{cod_prov : 12 , cod_part : 430, name_part : 'TUPUNGATO'},
{cod_prov : 17 , cod_part : 489, name_part : 'ULLUM'},
{cod_prov : 3 , cod_part : 140, name_part : 'UNION'},
{cod_prov : 7 , cod_part : 174, name_part : 'URUGUAY'},
{cod_prov : 22 , cod_part : 270, name_part : 'USHUAIA'},
{cod_prov : 10 , cod_part : 194, name_part : 'UTRACAN'},
{cod_prov : 15 , cod_part : 461, name_part : 'VALCHETA'},
{cod_prov : 17 , cod_part : 490, name_part : 'VALLE FERTIL'},
{cod_prov : 9 , cod_part : 391, name_part : 'VALLE GRANDE'},
{cod_prov : 2 , cod_part : 382, name_part : 'VALLE VIEJO'},
{cod_prov : 20 , cod_part : 262, name_part : 'VERA'},
{cod_prov : 1 , cod_part : 115, name_part : 'VICENTE LOPEZ'},
{cod_prov : 7 , cod_part : 175, name_part : 'VICTORIA'},
{cod_prov : 1 , cod_part : 365, name_part : 'VILLA GESELL'},
{cod_prov : 7 , cod_part : 176, name_part : 'VILLAGUAY'},
{cod_prov : 1 , cod_part : 116, name_part : 'VILLARINO'},
{cod_prov : 11 , cod_part : 425, name_part : 'VINCHINA'},
{cod_prov : 9 , cod_part : 187, name_part : 'YAVI'},
{cod_prov : 23 , cod_part : 528, name_part : 'YERBA BUENA'},
{cod_prov : 14 , cod_part : 454, name_part : 'ZAPALA'},
{cod_prov : 1 , cod_part : 117, name_part : 'ZARATE'},
{cod_prov : 17 , cod_part : 491, name_part : 'ZONDA'}];